### ISSUE TITLE
具体怎么使用啊大牛牛

### ISSUE THREAD

**Issue by skyformat99** [hl128k/tvbox#1]
电视上安装了TVbox

那这个url怎么使用啊

**Comment by hl128k** [comment]
tvbox里的设置->配置地址,然后从项目的tv目录里面挑一个喜欢的镜像分流，再选一个json，把这个镜像地址粘贴到配置地址就行了。例如https://gcore.jsdelivr.net/gh/hl128k/tvbox@main/tv/4/heroaku_dtes.json

**Comment by hl128k** [comment]
tvbox里的设置->配置地址,然后从项目的tv目录里面挑一个喜欢的镜像分流，再选一个json，把这个镜像地址粘贴到配置地址就行了。例如https://gcore.jsdelivr.net/gh/hl128k/tvbox@main/tv/4/heroaku_dtes.json

**Comment by hl128k** [comment]
使用可以参照这个https://github.com/Cyril0563/lanjing_live
加速的镜像你可以参照的https://github.com/liu673cn/box Github加速服务部分

**Comment by skyformat99** [comment]
谢谢大牛牛；推荐一个好用的吧json吧

**Comment by skyformat99** [comment]
> 谢谢大牛牛；推荐一个好用的吧json吧

谢谢大牛牛；推荐一个好用的吧json吧

**Comment by hl128k** [comment]
分流都差不多，具体那个json好用这就不好说了，建议自己试试吧具体地区可能效果还不一样，加进来的多少是可以的

**Comment by skyformat99** [comment]
> 分流都差不多，具体那个json好用这就不好说了，建议自己试试吧具体地区可能效果还不一样，加进来的多少是可以的

老兄给一个自己用的吧。找了半天好像都不是那么完美

**Comment by hl128k** [comment]
我现在用的这个Guard-H_fj.json，也可以试试这个里面的非GitHub的https://github.com/gaotianliuyun/gao

**Comment by skyformat99** [comment]
> 我现在用的这个Guard-H_fj.json，也可以试试这个里面的非GitHub的https://github.com/gaotianliuyun/gao

666
